name: Snyk SCA Analysis

on:
  workflow_call:
    inputs:
      manifest_path:
        required: false
        type: string
        description: "Path to the manifest file (package.json, pom.xml, etc.)"
        default: "."
      severity_threshold:
        required: false
        type: string
        description: "Minimum severity level to report (low, medium, high, critical)"
        default: "high"
      scan_dev_dependencies:
        required: false
        type: boolean
        description: "Whether to scan dev dependencies"
        default: false
      fail_on_issues:
        required: false
        type: boolean
        description: "Whether to fail the workflow if issues are found"
        default: true
      sarif_output:
        required: false
        type: boolean
        description: "Whether to output results as SARIF"
        default: true
    secrets:
      snyk_token:
        required: true
        description: "Snyk API token"

jobs:
  snyk-sca:
    name: Snyk SCA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk Auth
        run: snyk auth ${{ secrets.snyk_token }}
      
      - name: Run Snyk to check for vulnerabilities
        run: |
          ARGS="--severity-threshold=${{ inputs.severity_threshold }}"
          
          ${{ inputs.scan_dev_dependencies && 'ARGS="$ARGS --dev"' || '' }}
          ${{ inputs.fail_on_issues && 'ARGS="$ARGS --fail-on=all"' || 'ARGS="$ARGS --fail-on=upgradable"' }}
          ${{ inputs.sarif_output && 'ARGS="$ARGS --sarif-file-output=snyk-results.sarif"' || '' }}
          
          cd ${{ inputs.manifest_path }}
          snyk test $ARGS
        continue-on-error: ${{ !inputs.fail_on_issues }}

      - name: Upload Snyk Report to GitHub Code Scanning
        if: inputs.sarif_output
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ inputs.manifest_path == '.' && 'snyk-results.sarif' || format('{0}/snyk-results.sarif', inputs.manifest_path) }}
          category: "snyk-sca"