name: OWASP ZAP DAST Analysis

on:
  workflow_call:
    inputs:
      target_url:
        required: true
        type: string
        description: "URL to scan (e.g., https://example.com)"
      scan_type:
        required: false
        type: string
        description: "Type of scan (baseline, full, api)"
        default: "baseline"
      rules_file_path:
        required: false
        type: string
        description: "Path to ZAP rules configuration file"
        default: ""
      fail_on_issues:
        required: false
        type: boolean
        description: "Whether to fail the workflow if issues are found"
        default: false
      docker_name:
        required: false
        type: string
        description: "ZAP Docker image to use"
        default: "owasp/zap2docker-stable"
      cmd_options:
        required: false
        type: string
        description: "Additional command line options"
        default: "-a"

jobs:
  zap-scan:
    name: ZAP Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: ZAP Baseline Scan
        if: inputs.scan_type == 'baseline'
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: ${{ inputs.target_url }}
          rules_file_name: ${{ inputs.rules_file_path }}
          docker_name: ${{ inputs.docker_name }}
          cmd_options: ${{ inputs.cmd_options }}
          fail_action: ${{ inputs.fail_on_issues }}

      - name: ZAP Full Scan
        if: inputs.scan_type == 'full'
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: ${{ inputs.target_url }}
          rules_file_name: ${{ inputs.rules_file_path }}
          docker_name: ${{ inputs.docker_name }}
          cmd_options: ${{ inputs.cmd_options }}
          fail_action: ${{ inputs.fail_on_issues }}

      - name: ZAP API Scan
        if: inputs.scan_type == 'api'
        uses: zaproxy/action-api-scan@v0.3.0
        with:
          target: ${{ inputs.target_url }}
          rules_file_name: ${{ inputs.rules_file_path }}
          docker_name: ${{ inputs.docker_name }}
          cmd_options: ${{ inputs.cmd_options }}
          fail_action: ${{ inputs.fail_on_issues }}
          
      - name: Archive ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: |
            report.html
            zap.yaml
            zap.json
          retention-days: 30